#spring.application.name=profile-service

spring:
  application:
    name: profile-service # Name of the microservice
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true        # Enable H2 Console for web access
      path: /h2-console    # Access at http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update     # Automatically update schema for development
    show-sql: true          # Log SQL queries
    properties:
      hibernate:
        format_sql: true    # Pretty-print the SQL in logs
logging:
  level:
    root: INFO                  # Set the default logging level for the entire app
    org.hibernate.SQL: DEBUG    # Log SQL statements (already in place)
    org.hibernate.type: TRACE   # Log SQL parameter values (already in place)
    com.wfarooq.profile_service: DEBUG # Enable detailed logs for your specific package
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n" # Consistent log formatting

